# Generated by Django 5.0.1 on 2024-01-26 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Isapre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'isapre',
                'verbose_name_plural': 'isapres',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sub_titulo', models.CharField(max_length=100)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='noticias')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='noticias')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='noticias')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='noticias')),
                ('imagen5', models.ImageField(blank=True, null=True, upload_to='noticias')),
                ('comentario', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('isapre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.isapre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
            },
        ),
    ]
